name: plant_isce3_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pytest
  - gdal>=3.8
  - isce3>=0.25.0
  - plant>=0.8.0
  - numpy>=1.25.2
  - ruamel_yaml>=0.15
  - libnetcdf
  - matplotlib
  - scipy
  - h5py
  - libgdal-hdf5
  - libgdal-netcdf
  - libnetcdf
  - boto3
